// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminNav: typeof import('./src/components/general/AdminNav.vue')['default']
    Back: typeof import('./src/components/general/back.vue')['default']
    BlockButton: typeof import('./src/components/dropDown/BlockButton.vue')['default']
    BottomToolBarView: typeof import('./src/components/general/BottomToolBarView.vue')['default']
    CardSkeleton: typeof import('./src/components/general/CardSkeleton.vue')['default']
    CompanyCard: typeof import('./src/components/company/CompanyCard.vue')['default']
    ComputerCard: typeof import('./src/components/computer/ComputerCard.vue')['default']
    ComputerTable: typeof import('./src/components/computer/ComputerTable.vue')['default']
    ComputerTabledddd: typeof import('./src/components/computer/ComputerTabledddd.vue')['default']
    CreatorTable: typeof import('./src/components/tables/setting/CreatorTable.vue')['default']
    Edit: typeof import('./src/components/dropDown/Edit.vue')['default']
    EditButton: typeof import('./src/components/dropDown/EditButton.vue')['default']
    InputNumber: typeof import('./src/components/inputs/InputNumber.vue')['default']
    InputText: typeof import('./src/components/inputs/InputText.vue')['default']
    Loading: typeof import('./src/components/general/loading.vue')['default']
    LoadingFull: typeof import('./src/components/general/loadingFull.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    NamePage: typeof import('./src/components/general/namePage.vue')['default']
    Navbar: typeof import('./src/components/fixed/navbar.vue')['default']
    NumerInput: typeof import('./src/components/inputs/numerInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowButton: typeof import('./src/components/dropDown/ShowButton.vue')['default']
    ShowInput: typeof import('./src/components/inputs/ShowInput.vue')['default']
    ShowInputDate: typeof import('./src/components/inputs/ShowInputDate.vue')['default']
    ShowInputNumber: typeof import('./src/components/inputs/ShowInputNumber.vue')['default']
    ShowInputTest: typeof import('./src/components/inputs/ShowInputTest.vue')['default']
    ShowInputText: typeof import('./src/components/inputs/ShowInputText.vue')['default']
    Sidebar: typeof import('./src/components/fixed/sidebar.vue')['default']
    SkeletonTable: typeof import('./src/components/general/SkeletonTable.vue')['default']
    TableAll: typeof import('./src/components/general/TableAll.vue')['default']
    TestTable: typeof import('./src/components/computer/testTable.vue')['default']
    TextInput: typeof import('./src/components/general/TextInput.vue')['default']
    Toolbar: typeof import('./src/components/fixed/toolbar.vue')['default']
    TstView1: typeof import('./src/components/tstView1.vue')['default']
    ValidateInput: typeof import('./src/components/general/ValidateInput.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
