// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aaaaa: typeof import('./src/components/fixed/aaaaa.vue')['default']
    AdminNav: typeof import('./src/components/general/AdminNav.vue')['default']
    Back: typeof import('./src/components/general/back.vue')['default']
    BlockButton: typeof import('./src/components/dropDown/BlockButton.vue')['default']
    BottomToolBarView: typeof import('./src/components/general/BottomToolBarView.vue')['default']
    CardSkeleton: typeof import('./src/components/general/CardSkeleton.vue')['default']
    CreatorTable: typeof import('./src/components/tables/setting/CreatorTable.vue')['default']
    DeleteButton: typeof import('./src/components/dropDown/DeleteButton.vue')['default']
    DragDrop: typeof import('./src/components/DragDrop.vue')['default']
    DragDropFilePreview: typeof import('./src/components/DragDropFilePreview.vue')['default']
    DuplicateButton: typeof import('./src/components/dropDown/DuplicateButton.vue')['default']
    EditButton: typeof import('./src/components/dropDown/EditButton.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    InputNumber: typeof import('./src/components/inputs/InputNumber.vue')['default']
    InputText: typeof import('./src/components/inputs/InputText.vue')['default']
    Loading: typeof import('./src/components/general/loading.vue')['default']
    LoadingFull: typeof import('./src/components/general/loadingFull.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    NamePage: typeof import('./src/components/general/namePage.vue')['default']
    NavBar: typeof import('./src/components/fixed/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowButton: typeof import('./src/components/dropDown/ShowButton.vue')['default']
    ShowInputNumber: typeof import('./src/components/inputs/ShowInputNumber.vue')['default']
    ShowInputText: typeof import('./src/components/inputs/ShowInputText.vue')['default']
    SideBar: typeof import('./src/components/fixed/sideBar.vue')['default']
    SimpleLoading: typeof import('./src/components/general/SimpleLoading.vue')['default']
    SkeletonTable: typeof import('./src/components/general/SkeletonTable.vue')['default']
    TableAll: typeof import('./src/components/general/TableAll.vue')['default']
    TextInput: typeof import('./src/components/general/TextInput.vue')['default']
    ToolBar: typeof import('./src/components/fixed/toolBar.vue')['default']
    TstView1: typeof import('./src/components/tstView1.vue')['default']
    ValidateInput: typeof import('./src/components/general/ValidateInput.vue')['default']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
