import fs from "node:fs";
import { fileURLToPath, URL } from "node:url";
import js from "@eslint/js";
import { globalIgnores, includeIgnoreFile } from "eslint/config";
import pluginVue from "eslint-plugin-vue";
import {
  defineConfigWithVueTs,
  vueTsConfigs,
} from "@vue/eslint-config-typescript";
import prettier from "@vue/eslint-config-prettier";

// .eslintrc-auto-import.json is generated by unplugin-auto-import. A static
// import would take linting down entirely whenever it is missing (fresh clone
// before the first build, clean checkout, CI cache miss), so read it softly.
function readAutoImportGlobals() {
  const path = fileURLToPath(
    new URL(".eslintrc-auto-import.json", import.meta.url)
  );
  let globals;
  try {
    globals = JSON.parse(fs.readFileSync(path, "utf8")).globals ?? {};
  } catch {
    return {};
  }
  // The generator writes every name as `true`; flat config wants a severity.
  return Object.fromEntries(
    Object.keys(globals).map((name) => [name, "readonly"])
  );
}

export default defineConfigWithVueTs(
  // Replaces the old `--ignore-path .gitignore` CLI flag.
  includeIgnoreFile(fileURLToPath(new URL(".gitignore", import.meta.url))),
  globalIgnores(["dev-dist/**", "public/sw.js"]),

  {
    name: "app/files-to-lint",
    files: ["**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx,vue}"],
    languageOptions: {
      ecmaVersion: "latest",
      globals: readAutoImportGlobals(),
    },
  },

  {
    // postcss.config.cjs and friends are CommonJS, not ESM.
    name: "app/commonjs-files",
    files: ["**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: {
        module: "writable",
        require: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
  },

  // The old .eslintrc.cjs extended "eslint:recommended"; vueTsConfigs.recommended
  // only carries typescript-eslint's rules plus the eslint-recommended
  // *overrides*, so the core rules have to be enabled explicitly.
  js.configs.recommended,
  pluginVue.configs["flat/essential"],
  vueTsConfigs.recommended,
  prettier,

  {
    name: "app/rules",
    rules: {
      // The project treats formatting drift as a hard failure; the shared
      // config only warns. endOfLine lives in .prettierrc.json.
      "prettier/prettier": "error",
    },
  }
);
