export enum EnumInputType {
  Text = "text",
  Number = "number",
  Password = "password",
  Email = "email",
  Date = "date",
  Time = "time",
  DateTime = "datetime",
  Tel = "tel",
  Url = "url",
  Search = "search",
  Range = "range",
  Color = "color",
  File = "file",
  Hidden = "hidden",
}
